require("dotenv").config();

module.exports = {
  SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET,
  SLACK_BOT_TOKEN: process.env.SLACK_BOT_TOKEN,
  SLACK_APP_TOKEN: process.env.SLACK_APP_TOKEN,

  PIPEFY_TOKEN: process.env.PIPEFY_TOKEN,
  PIPE_ID_EVENTO_RISCO: process.env.PIPE_ID_EVENTO_RISCO,
  PIPE_ID_NOVO_FORNECEDOR: process.env.PIPE_ID_NOVO_FORNECEDOR,
  PIPE_ID_PAGAMENTO_RH: process.env.PIPE_ID_PAGAMENTO_RH,
  PIPE_ID_REEMBOLSO: process.env.PIPE_ID_REEMBOLSO,
  PIPE_ID_PAGAMENTO: process.env.PIPE_ID_PAGAMENTO,
};
